[package]
name = "rlr-gtk"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "pixel screen ruler"
repository = "https://github.com/epilys/rlr"

[dependencies]
gtk = "0.14.3"

[[bin]]
name = "rlr"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
