[package]
name = "rlr"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "pixel screen ruler"
repository = "https://github.com/epilys/rlr"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.14.3"


[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
